### ISSUE TITLE
Search using WordPress API

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#109]
## Is your feature request related to a problem? Please describe.

Instead of using state management (*state.js*) to search, implement search functionality using the WordPress API

## Describe the solution you'd like

Two API calls will be needed:
`https://wecount.inclusivedesign.ca/wp-json/wp/v2/posts?search=query`
`https://wecount.inclusivedesign.ca/wp-json/wp/v2/pages?search=query`

The results from these calls will then need to be combined and served to the client

**Comment by jobara** [comment]
@cindyli should we leave a comment here about why we've closed this issue. Might be helpful for the future if we want to revisit or can't remember why.

**Comment by cindyli** [comment]
> @cindyli should we leave a comment here about why we've closed this issue. Might be helpful for the future if we want to revisit or can't remember why.

Good point. Thanks for reminding.

The intention of this issue is to perform user search queries via the WordPress API: every search query will be sent to the back-end WordPress and the site will display the results returned by WordPress.

As WeCount website will always work with a static set of data (every time when the WeCount team edits data via WordPress admin, the WeCount website will be rebuilt to reflect the changed data), and the Vue Store has been improved to fetch the data, including news, views, site pages, once and re-use them afterwards, so it would be more efficient to search across the fetched data rather than making trips to the back-end API for every search.

The latter solution has already been implemented. This issue can be closed.
