### ISSUE TITLE
Tag results using WordPress API

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#110]
## Is your feature request related to a problem? Please describe.

Instead of using state management (state.js) to produce tag results, implement functionality using the WordPress API

## Describe the solution you'd like

Tags are queried by term_id in the API: 
`https://wecount.inclusivedesign.ca/wp-json/wp/v2/posts?tags=5`

1. Creat dictionary of where keys are tag names and value are tag term_id
2. replace querying the state with the API call using the dictionary created in the previous step to get correct term_id: 
`https://wecount.inclusivedesign.ca/wp-json/wp/v2/posts?tags=tagDict["Accessibility"]`

*tagDict["Accessibility"] = 5*

**Comment by cindyli** [comment]
This issue is related to https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/90.

As https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/90 was assigned to me, I also pondered over how to generate routes in nuxt.config.js for rendering tags pages statically. Here's my thoughts:

1. Use wordpress API `https://wecount.inclusivedesign.ca/wp-json/wp/v2/tags` to find all tags;
2. Loop thru these tags to do:
2.1 In each tag record, `{tagRec}._link.wp:post_type.0.href` shows the URL for retrieving all posts marked with this tag;
2.2 Use this URL to fetch all posts and generate routes for each page: `/tag/{tagName}/{pageNumber}`

When a user clicks on a tag for example "inclusive", the page will be redirected to the first page listing posts for this tag - "/tag/inclusive/1". 

Let's talk about these approaches when the styling work is out of way. Cheers!
