### ISSUE TITLE
Tags is being listed in side menu items for post pages

### ISSUE THREAD

**Issue by TeddTech** [inclusive-design/wecount.inclusivedesign.ca#313]
## Describe the bug

Tags is showing up as a side menu item when on a post page.

## To Reproduce

Steps to reproduce the behaviour:

1. Go to dev site
2. Navigate to views page
3. Click on any posts
4. Observe side menu to see error

## Expected behaviour

Tags should not be listed in the side menu.

## Screenshots

<img width="1027" alt="Screen Shot 2020-06-25 at 2 47 33 PM" src="https://user-images.githubusercontent.com/25180846/85798765-e6dff800-b6f2-11ea-9a45-50d70abaec2a.png">

## Additional context

N/A

**Comment by cindyli** [comment]
@uttaraghodke & @lliskovoi, the issue described above can be seen on any post page such as [this one](https://dev--wecount.netlify.app/views/the-importance-of-peripheral-vision/).

This is because the "Tags" title was changed recently from `h3` to `h2` due to the fix to [this issue](https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/309). Now the side menu picks up the "Tags" heading.

Personally, I think it is a good feature rather than a bug that the "Tags" title shows up on the side menu so users can click on it to jump to the tags section.

What do you think? Is it OK to have "Tags" title displayed on the side menu?

**Comment by uttaraghodke** [comment]
@cindyli I think it seems fine too me. It is not a problem if Tags appears in the side menu.

**Comment by cindyli** [comment]
Closed as to @uttaraghodke's suggestion above.
